import json
from dataclasses import dataclass
from typing import Optional

@dataclass
class ACLRule:
    action: str
    src: list
    dst: list
    proto: Optional[str] = None

    def to_dict(self) -> dict:
        rule = {"action": self.action, "src": self.src, "dst": self.dst}
        if self.proto:
            rule["proto"] = self.proto
        return rule
    
    
@dataclass
class HeadscalePolicy:
    tag_owners: dict
    acls: list[ACLRule]
    auto_approvers: dict
    hosts: dict = None

    def to_dict(self) -> dict:
        policy = {
            "tagOwners": self.tag_owners,
            "acls": [rule.to_dict() for rule in self.acls],
            "autoApprovers": self.auto_approvers,
        }
        if self.hosts:
            policy["hosts"] = self.hosts
        return policy

    def to_hujson(self) -> str:
        header = "// Auto-generated by cyberrange-acl-verifier. Do not edit manually.\n"
        return header + json.dumps(self.to_dict(), indent=2)
