import json
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ACLRule:
    action: str
    src: list
    dst: list
    # Note: proto is present for model completeness but is NOT used in ACL generation
    # or verification. Port/protocol-level isolation is handled by AWS security groups.
    # Headscale ACLs in this project are purely identity-based (who can reach whom),
    # not port-filtered. Do not add port logic here without updating the executor too.
    proto: Optional[str] = None

    def to_dict(self) -> dict:
        rule = {"action": self.action, "src": self.src, "dst": self.dst}
        if self.proto:
            rule["proto"] = self.proto
        return rule


@dataclass
class HeadscalePolicy:
    tag_owners: dict
    acls: list[ACLRule]
    auto_approvers: dict
    hosts: Optional[dict] = None

    def to_dict(self) -> dict:
        policy = {
            "tagOwners": self.tag_owners,
            "acls": [rule.to_dict() for rule in self.acls],
            "autoApprovers": self.auto_approvers,
        }
        if self.hosts:
            policy["hosts"] = self.hosts
        return policy

    def to_hujson(self) -> str:
        header = "// Auto-generated by cyberrange-acl-verifier. Do not edit manually.\n"
        return header + json.dumps(self.to_dict(), indent=2)